name: nutri_glow
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.1
  uuid: ^4.4.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
